name: build-yara-multiarch-and-merge-rules

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RULES_REPO_1: https://github.com/Yara-Rules/rules.git
  RULES_REPO_2: https://github.com/Neo23x0/Loki.git

jobs:
  merge-rules:
    name: Merge community rules
    runs-on: ubuntu-latest
    outputs:
      combined_path: ${{ steps.combine.outputs.combined }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch community rules
        run: |
          git clone --depth 1 $RULES_REPO_1 /tmp/yara_rules_repo1 || true
          git clone --depth 1 $RULES_REPO_2 /tmp/loki_repo || true
      - name: Run merge script
        id: combine
        run: |
          mkdir -p merged_rules
          # copy .yar files from Yara-Rules and Loki signature-base
          find /tmp/yara_rules_repo1 -type f -name '*.yar' -print0 | xargs -0 -I{} cp {} merged_rules/ || true
          find /tmp/loki_repo/signature-base/yara -type f -name '*.yar' -print0 | xargs -0 -I{} cp {} merged_rules/ || true
          # run python dedupe to produce all_rules_combined.yar
          python3 ./scripts/merge_rules.py merged_rules all_rules_combined.yar
          ls -l all_rules_combined.yar
          echo "::set-output name=combined::$(pwd)/all_rules_combined.yar"
      - name: Upload combined rules
        uses: actions/upload-artifact@v4
        with:
          name: all_rules_combined
          path: all_rules_combined.yar

  build-linux-amd64:
    name: Build Linux amd64
    runs-on: ubuntu-latest
    needs: merge-rules
    steps:
      - uses: actions/checkout@v4
      - name: Download combined rules
        uses: actions/download-artifact@v4
        with:
          name: all_rules_combined
      - name: Build YARA (amd64)
        run: |
          ./scripts/build_yara.sh out
      - name: Add rules into artifact dir
        run: |
          mkdir -p out/rules
          cp all_rules_combined.yar out/rules/
      - name: Pack artifact
        run: |
          tar -C out -czf yara-linux-amd64.tar.gz out || true
      - uses: actions/upload-artifact@v4
        with:
          name: yara-linux-amd64
          path: yara-linux-amd64.tar.gz

  build-linux-arm64:
    name: Build Linux aarch64 (ARM64)
    runs-on: ubuntu-latest
    needs: merge-rules
    steps:
      - uses: actions/checkout@v4
      - name: Download combined rules
        uses: actions/download-artifact@v4
        with:
          name: all_rules_combined
      - name: Setup QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build inside arm64 container
        run: |
          ./scripts/build_yara_arm_docker.sh out
      - name: Add rules into artifact dir
        run: |
          mkdir -p out/rules
          cp all_rules_combined.yar out/rules/
      - name: Pack artifact
        run: |
          tar -C out -czf yara-linux-arm64.tar.gz out || true
      - uses: actions/upload-artifact@v4
        with:
          name: yara-linux-arm64
          path: yara-linux-arm64.tar.gz

  build-windows:
    name: Build Windows x64 & x86 (MSYS2 / mingw)
    runs-on: windows-latest
    needs: merge-rules
    steps:
      - uses: actions/checkout@v4
      - name: Download combined rules
        uses: actions/download-artifact@v4
        with:
          name: all_rules_combined
      - name: Setup MSYS2 (MINGW64 and MINGW32)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-i686-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-i686-cmake
      - name: Build x64 & x86 yara (msys2)
        shell: msys2 {0}
        run: |
          set -e
          # build x64
          git clone --depth 1 https://github.com/VirusTotal/yara.git
          mkdir -p yara/build_x64 && cd yara/build_x64
          # ensure target compatibility with Win2003: define _WIN32_WINNT=0x0502 and try static link
          CFLAGS="-D_WIN32_WINNT=0x0502 -static-libgcc -static-libstdc++" cmake -G "MinGW Makefiles" .. -DCMAKE_BUILD_TYPE=Release
          mingw32-make -j%NUMBER_OF_PROCESSORS%
          mkdir -p $GITHUB_WORKSPACE/out_x64/bin
          cp src/yara.exe $GITHUB_WORKSPACE/out_x64/bin/ || true
          cd $GITHUB_WORKSPACE
          # build x86
          mkdir -p yara/build_x86 && cd yara/build_x86
          CFLAGS="-D_WIN32_WINNT=0x0502 -m32 -static-libgcc -static-libstdc++" cmake -G "MinGW Makefiles" .. -DCMAKE_BUILD_TYPE=Release
          mingw32-make -j%NUMBER_OF_PROCESSORS%
          mkdir -p $GITHUB_WORKSPACE/out_x86/bin
          cp src/yara.exe $GITHUB_WORKSPACE/out_x86/bin/ || true
      - name: Add rules into artifact dir
        run: |
          mkdir -p out_x64/rules out_x86/rules
          cp all_rules_combined.yar out_x64/rules/
          cp all_rules_combined.yar out_x86/rules/
      - name: Pack artifacts
        run: |
          powershell -Command "Compress-Archive -Path out_x64 -DestinationPath yara-win-x64.zip -Force"
          powershell -Command "Compress-Archive -Path out_x86 -DestinationPath yara-win-x86.zip -Force"
      - uses: actions/upload-artifact@v4
        with:
          name: yara-win-x64
          path: yara-win-x64.zip
      - uses: actions/upload-artifact@v4
        with:
          name: yara-win-x86
          path: yara-win-x86.zip